apiVersion: v1
kind: Pod
metadata:
  name: pod-init
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: data-vol
      mountPath: /usr/share/nginx/html
  initContainers:
  - image: alpine
    name: r-n-g
    command: ["/bin/sh", "-c", "shuf -i 0-100 -n 1 >> /usr/share/nginx/html/index.html"]
    volumeMounts:
    - name: data-vol
      mountPath: /usr/share/nginx/html
  volumes:
  - name: data-vol
    hostPath:
      path: /data
      type: Directory

