apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-with-cm
  name: nginx-with-cm
spec:
  containers:
    - image: nginx
      name: nginx-with-cm
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /usr/share/nginx/html/index.html
          name: html
          subPath: index.html
  volumes:
    - name: html
      configMap:
        name: nginx-cm
