apiVersion: v1
kind: Pod
metadata:
  name: pod-with-logs
spec:
  containers:
    - image: nginx
      name: nginx
      ports:
        - containerPort: 80
    - image: tomcat
      name: tomcat
      ports:
        - containerPort: 8080

