apiVersion: v1
kind: Pod
metadata:
  name: custom-command
  labels:
    run: 'custom-command'
spec:
  containers:
    - name: custom-command
      image: alpine
      command: ["echo", "hello alpine"]
