apiVersion: v1
kind: Pod
metadata:
  name: limited-web
spec:
  containers:
    - name: limited-web
      image: httpd
      resources:
        requests:
          memory: "100Mi"
          cpu: "100m"
        limits:
          memory: "200Mi"
          cpu: "200m"
