apiVersion: v1
kind: Pod
metadata:
  name: web-node-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: env
            operator: In
            values:
            - test         
      # preferredDuringSchedulingIgnoredDuringExecution:
      # - weight: 1
      #   preference:
      #     matchExpressions:
      #     - key: env
      #       operator: In
      #       values:
      #       - 
  containers:
    - name: web-node-affinity
      image: nginx
      ports:
        - containerPort: 80
